/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ActionId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionId
        //private ActionId instance;

        public ActionIdTests()
        {
            // TODO uncomment below to create an instance of ActionId
            //instance = new ActionId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionId
        /// </summary>
        [Fact]
        public void ActionIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionId
            //Assert.IsType<ActionId>(instance);
        }


        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'Activity'
        /// </summary>
        [Fact]
        public void ActivityTest()
        {
            // TODO unit test for the property 'Activity'
        }
        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }

    }

}
