/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AmazonSqsNotificationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AmazonSqsNotificationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AmazonSqsNotificationType
        //private AmazonSqsNotificationType instance;

        public AmazonSqsNotificationTypeTests()
        {
            // TODO uncomment below to create an instance of AmazonSqsNotificationType
            //instance = new AmazonSqsNotificationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AmazonSqsNotificationType
        /// </summary>
        [Fact]
        public void AmazonSqsNotificationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AmazonSqsNotificationType
            //Assert.IsType<AmazonSqsNotificationType>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ApiKeyRef'
        /// </summary>
        [Fact]
        public void ApiKeyRefTest()
        {
            // TODO unit test for the property 'ApiKeyRef'
        }
        /// <summary>
        /// Test the property 'ApiSecretRef'
        /// </summary>
        [Fact]
        public void ApiSecretRefTest()
        {
            // TODO unit test for the property 'ApiSecretRef'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'QueueUrlRef'
        /// </summary>
        [Fact]
        public void QueueUrlRefTest()
        {
            // TODO unit test for the property 'QueueUrlRef'
        }

    }

}
