/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiRequestNotificationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiRequestNotificationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiRequestNotificationType
        //private ApiRequestNotificationType instance;

        public ApiRequestNotificationTypeTests()
        {
            // TODO uncomment below to create an instance of ApiRequestNotificationType
            //instance = new ApiRequestNotificationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiRequestNotificationType
        /// </summary>
        [Fact]
        public void ApiRequestNotificationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiRequestNotificationType
            //Assert.IsType<ApiRequestNotificationType>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'HttpMethod'
        /// </summary>
        [Fact]
        public void HttpMethodTest()
        {
            // TODO unit test for the property 'HttpMethod'
        }
        /// <summary>
        /// Test the property 'PathAndQuery'
        /// </summary>
        [Fact]
        public void PathAndQueryTest()
        {
            // TODO unit test for the property 'PathAndQuery'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
