/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Attempt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttemptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Attempt
        //private Attempt instance;

        public AttemptTests()
        {
            // TODO uncomment below to create an instance of Attempt
            //instance = new Attempt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Attempt
        /// </summary>
        [Fact]
        public void AttemptInstanceTest()
        {
            // TODO uncomment below to test "IsType" Attempt
            //Assert.IsType<Attempt>(instance);
        }


        /// <summary>
        /// Test the property 'AttemptNumber'
        /// </summary>
        [Fact]
        public void AttemptNumberTest()
        {
            // TODO unit test for the property 'AttemptNumber'
        }
        /// <summary>
        /// Test the property 'AttemptTime'
        /// </summary>
        [Fact]
        public void AttemptTimeTest()
        {
            // TODO unit test for the property 'AttemptTime'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
