/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateNotificationRequestNotificationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateNotificationRequestNotificationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateNotificationRequestNotificationType
        //private CreateNotificationRequestNotificationType instance;

        public CreateNotificationRequestNotificationTypeTests()
        {
            // TODO uncomment below to create an instance of CreateNotificationRequestNotificationType
            //instance = new CreateNotificationRequestNotificationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateNotificationRequestNotificationType
        /// </summary>
        [Fact]
        public void CreateNotificationRequestNotificationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateNotificationRequestNotificationType
            //Assert.IsType<CreateNotificationRequestNotificationType>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ApiKeyRef'
        /// </summary>
        [Fact]
        public void ApiKeyRefTest()
        {
            // TODO unit test for the property 'ApiKeyRef'
        }
        /// <summary>
        /// Test the property 'ApiSecretRef'
        /// </summary>
        [Fact]
        public void ApiSecretRefTest()
        {
            // TODO unit test for the property 'ApiSecretRef'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'QueueUrlRef'
        /// </summary>
        [Fact]
        public void QueueUrlRefTest()
        {
            // TODO unit test for the property 'QueueUrlRef'
        }
        /// <summary>
        /// Test the property 'HttpMethod'
        /// </summary>
        [Fact]
        public void HttpMethodTest()
        {
            // TODO unit test for the property 'HttpMethod'
        }
        /// <summary>
        /// Test the property 'PathAndQuery'
        /// </summary>
        [Fact]
        public void PathAndQueryTest()
        {
            // TODO unit test for the property 'PathAndQuery'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'PlainTextBody'
        /// </summary>
        [Fact]
        public void PlainTextBodyTest()
        {
            // TODO unit test for the property 'PlainTextBody'
        }
        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Fact]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }
        /// <summary>
        /// Test the property 'EmailAddressTo'
        /// </summary>
        [Fact]
        public void EmailAddressToTest()
        {
            // TODO unit test for the property 'EmailAddressTo'
        }
        /// <summary>
        /// Test the property 'EmailAddressCc'
        /// </summary>
        [Fact]
        public void EmailAddressCcTest()
        {
            // TODO unit test for the property 'EmailAddressCc'
        }
        /// <summary>
        /// Test the property 'EmailAddressBcc'
        /// </summary>
        [Fact]
        public void EmailAddressBccTest()
        {
            // TODO unit test for the property 'EmailAddressBcc'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Fact]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'AuthenticationType'
        /// </summary>
        [Fact]
        public void AuthenticationTypeTest()
        {
            // TODO unit test for the property 'AuthenticationType'
        }
        /// <summary>
        /// Test the property 'AuthenticationConfigurationItemPaths'
        /// </summary>
        [Fact]
        public void AuthenticationConfigurationItemPathsTest()
        {
            // TODO unit test for the property 'AuthenticationConfigurationItemPaths'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

    }

}
