/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateNotificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateNotificationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateNotificationRequest
        //private CreateNotificationRequest instance;

        public CreateNotificationRequestTests()
        {
            // TODO uncomment below to create an instance of CreateNotificationRequest
            //instance = new CreateNotificationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateNotificationRequest
        /// </summary>
        [Fact]
        public void CreateNotificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateNotificationRequest
            //Assert.IsType<CreateNotificationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'NotificationId'
        /// </summary>
        [Fact]
        public void NotificationIdTest()
        {
            // TODO unit test for the property 'NotificationId'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'NotificationType'
        /// </summary>
        [Fact]
        public void NotificationTypeTest()
        {
            // TODO unit test for the property 'NotificationType'
        }

    }

}
