/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubscription
        //private CreateSubscription instance;

        public CreateSubscriptionTests()
        {
            // TODO uncomment below to create an instance of CreateSubscription
            //instance = new CreateSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubscription
        /// </summary>
        [Fact]
        public void CreateSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubscription
            //Assert.IsType<CreateSubscription>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MatchingPattern'
        /// </summary>
        [Fact]
        public void MatchingPatternTest()
        {
            // TODO unit test for the property 'MatchingPattern'
        }

    }

}
