/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EmailNotificationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailNotificationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailNotificationType
        //private EmailNotificationType instance;

        public EmailNotificationTypeTests()
        {
            // TODO uncomment below to create an instance of EmailNotificationType
            //instance = new EmailNotificationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailNotificationType
        /// </summary>
        [Fact]
        public void EmailNotificationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailNotificationType
            //Assert.IsType<EmailNotificationType>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'PlainTextBody'
        /// </summary>
        [Fact]
        public void PlainTextBodyTest()
        {
            // TODO unit test for the property 'PlainTextBody'
        }
        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Fact]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }
        /// <summary>
        /// Test the property 'EmailAddressTo'
        /// </summary>
        [Fact]
        public void EmailAddressToTest()
        {
            // TODO unit test for the property 'EmailAddressTo'
        }
        /// <summary>
        /// Test the property 'EmailAddressCc'
        /// </summary>
        [Fact]
        public void EmailAddressCcTest()
        {
            // TODO unit test for the property 'EmailAddressCc'
        }
        /// <summary>
        /// Test the property 'EmailAddressBcc'
        /// </summary>
        [Fact]
        public void EmailAddressBccTest()
        {
            // TODO unit test for the property 'EmailAddressBcc'
        }

    }

}
