/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EventTypeSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventTypeSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventTypeSchema
        //private EventTypeSchema instance;

        public EventTypeSchemaTests()
        {
            // TODO uncomment below to create an instance of EventTypeSchema
            //instance = new EventTypeSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventTypeSchema
        /// </summary>
        [Fact]
        public void EventTypeSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventTypeSchema
            //Assert.IsType<EventTypeSchema>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'JsonSchema'
        /// </summary>
        [Fact]
        public void JsonSchemaTest()
        {
            // TODO unit test for the property 'JsonSchema'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Fact]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
