/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ManualEventBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManualEventBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManualEventBody
        //private ManualEventBody instance;

        public ManualEventBodyTests()
        {
            // TODO uncomment below to create an instance of ManualEventBody
            //instance = new ManualEventBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualEventBody
        /// </summary>
        [Fact]
        public void ManualEventBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManualEventBody
            //Assert.IsType<ManualEventBody>(instance);
        }


        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'JsonMessage'
        /// </summary>
        [Fact]
        public void JsonMessageTest()
        {
            // TODO unit test for the property 'JsonMessage'
        }

    }

}
