/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ManualEventRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManualEventRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManualEventRequest
        //private ManualEventRequest instance;

        public ManualEventRequestTests()
        {
            // TODO uncomment below to create an instance of ManualEventRequest
            //instance = new ManualEventRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualEventRequest
        /// </summary>
        [Fact]
        public void ManualEventRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManualEventRequest
            //Assert.IsType<ManualEventRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
