/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ManualEventHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManualEventHeaderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManualEventHeader
        //private ManualEventHeader instance;

        public ManualEventHeaderTests()
        {
            // TODO uncomment below to create an instance of ManualEventHeader
            //instance = new ManualEventHeader();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualEventHeader
        /// </summary>
        [Fact]
        public void ManualEventHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManualEventHeader
            //Assert.IsType<ManualEventHeader>(instance);
        }


        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Fact]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
