/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Finbourne.Notifications.Sdk.Model;
using Finbourne.Notifications.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Finbourne.Notifications.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceListOfSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceListOfSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceListOfSubscription
        //private ResourceListOfSubscription instance;

        public ResourceListOfSubscriptionTests()
        {
            // TODO uncomment below to create an instance of ResourceListOfSubscription
            //instance = new ResourceListOfSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceListOfSubscription
        /// </summary>
        [Fact]
        public void ResourceListOfSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceListOfSubscription
            //Assert.IsType<ResourceListOfSubscription>(instance);
        }


        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Fact]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'PreviousPage'
        /// </summary>
        [Fact]
        public void PreviousPageTest()
        {
            // TODO unit test for the property 'PreviousPage'
        }

    }

}
