/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Finbourne.Notifications.Sdk.Client;
using Finbourne.Notifications.Sdk.Api;
// uncomment below to import models
//using Finbourne.Notifications.Sdk.Model;

namespace Finbourne.Notifications.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing ManualEventApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ManualEventApiTests : IDisposable
    {
        private ManualEventApi instance;

        public ManualEventApiTests()
        {
            instance = new ManualEventApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualEventApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ManualEventApi
            //Assert.IsType<ManualEventApi>(instance);
        }

        /// <summary>
        /// Test TriggerManualEvent
        /// </summary>
        [Fact]
        public void TriggerManualEventTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ManualEventRequest manualEventRequest = null;
            //var response = instance.TriggerManualEvent(manualEventRequest);
            //Assert.IsType<ManualEvent>(response);
        }
    }
}
